apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    {{- toYaml .Values.admin_api.annotations | nindent 4 }}
  labels:
    app: {{ template "cortex.name" . }}-admin-api
    chart: {{ template "cortex.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "cortex.fullname" . }}-admin-api
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.admin_api.replicas }}
  selector:
    matchLabels:
      app: {{ template "cortex.name" . }}-admin-api
      release: {{ .Release.Name }}
  strategy:
    {{- toYaml .Values.admin_api.strategy | nindent 4 }}
  template:
    metadata:
      labels:
        app: {{ template "cortex.name" . }}-admin-api
        name: {{ template "cortex.name" . }}-admin-api
        target: admin-api
        release: {{ .Release.Name }}
        {{- with .Values.admin_api.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- if .Values.useExternalConfig }}
        checksum/config: {{ .Values.externalConfigVersion }}
        {{- else }}
        checksum/config: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- end}}
        {{- with .Values.admin_api.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ template "cortex.serviceAccountName" . }}
      {{- if .Values.admin_api.priorityClassName }}
      priorityClassName: {{ .Values.admin_api.priorityClassName }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.admin_api.securityContext | nindent 8 }}
      initContainers:
        {{- toYaml .Values.admin_api.initContainers | nindent 8 }}
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "-target=admin_api"
            - "-config.file=/etc/cortex/cortex.yaml"
            - "-config.file=/etc/metrics-enterprise/metrics-enterprise.yaml"
            {{- if .Values.minio.enabled }}
            - -admin-client.storage.s3.endpoint={{ "metrics_enterprise.fullname" . }}-minio.{{ .Release.Namespace }}.svc.cluster.local:9000
            - -admin-client.storage.s3.bucket-name=metrics-enterprise-tsdb
            - -admin-client.storage.s3.access-key-id=metrics-enterprise
            - -admin-client.storage.s3.secret-access-key=supersecret
            - -admin-client.storage.s3.insecure=true
            {{- end }}
            {{- range $key, $value := .Values.admin_api.extraArgs }}
            - "-{{ $key }}={{ $value }}"
            {{- end }}
          volumeMounts:
            {{- if .Values.admin_api.extraVolumeMounts }}
              {{ toYaml .Values.admin_api.extraVolumeMounts | nindent 12}}
            {{- end }}
            - name: config
              mountPath: /etc/cortex
            - name: storage
              mountPath: "/data"
              subPath: {{ .Values.admin_api.persistence.subPath }}
          ports:
            - name: http-metrics
              containerPort: {{ .Values.config.server.http_listen_port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.admin_api.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.admin_api.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.admin_api.resources | nindent 12 }}
          securityContext:
            readOnlyRootFilesystem: true
          env:
            {{- if .Values.admin_api.env }}
            {{ toYaml .Values.admin_api.env | nindent 12 }}
            {{- end }}
        {{- with .Values.admin_api.extraContainers }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
      nodeSelector:
        {{- toYaml .Values.admin_api.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.admin_api.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.admin_api.tolerations | nindent 8 }}
      terminationGracePeriodSeconds: {{ .Values.admin_api.terminationGracePeriodSeconds }}
      volumes:
        - name: config
          secret:
          {{- if .Values.useExternalConfig }}
            secretName: {{ .Values.externalConfigSecretName }}
          {{- else }}
            secretName: {{ template "cortex.fullname" . }}
          {{- end }}
        {{- if .Values.admin_api.extraVolumes }}
        {{ toYaml .Values.admin_api.extraVolumes | nindent 8}}
        {{- end }}
        - name: storage
          emptyDir: {}
