apiVersion: v1
kind: Service
metadata:
  name: {{ template "cortex.fullname" . }}-admin-api
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "cortex.name" . }}-admin-api
    chart: {{ template "cortex.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- with .Values.admin_api.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.admin_api.annotations | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.config.server.http_listen_port }}
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
  selector:
    app: {{ template "cortex.name" . }}-admin-api
    release: {{ .Release.Name }}
