{{- if not .Values.bootstrap -}}
{{- $clusterPort := regexReplaceAll ".+[:]" (default "0.0.0.0:9094" .Values.config.alertmanager.cluster_bind_address) "" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "metrics_enterprise.fullname" . }}-alertmanager-headless
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "metrics_enterprise.name" . }}-alertmanager
    chart: {{ template "metrics_enterprise.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- with .Values.alertmanager.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.alertmanager.service.annotations | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: {{ .Values.config.server.http_listen_port }}
      protocol: TCP
      name: http-metrics
    - port: {{ $clusterPort }}
      protocol: TCP
      name: cluster
  selector:
    app: {{ template "metrics_enterprise.name" . }}-alertmanager
    release: {{ .Release.Name }}
{{- end -}}
