{{- if .Values.nginx.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "metrics_enterprise.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "metrics_enterprise.name" . }}-nginx
    chart: {{ template "metrics_enterprise.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- with .Values.nginx.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.nginx.annotations | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.nginx.http_listen_port }}
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
  selector:
    app: {{ template "metrics_enterprise.name" . }}-nginx
    release: {{ .Release.Name }}
{{- end }}