{{- if not .Values.bootstrap -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "metrics_enterprise.fullname" . }}-ruler
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "metrics_enterprise.name" . }}-ruler
    chart: {{ template "metrics_enterprise.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- with .Values.ruler.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.ruler.annotations | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.config.server.http_listen_port }}
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
  selector:
    app: {{ template "metrics_enterprise.name" . }}-ruler
    release: {{ .Release.Name }}
{{- end -}}
