{{- if and .Values.configsdb_postgresql.enabled .Values.configsdb_postgresql.auth.password -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "metrics_enterprise.fullname" . }}-postgresql
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "metrics_enterprise.name" . }}
    chart: {{ template "metrics_enterprise.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  postgresql-password: {{ .Values.configsdb_postgresql.auth.password | b64enc}}
{{- end }}